name: deploy-ui

on:
  push:
    paths:
      - ui/**
      - .github/**
    branches:
    - main

jobs:
  test-ui:
    name: Test UI
    uses: ./.github/workflows/reusable-test-node.yaml
    with:
      component: apps/ui
  deploy-ui:
    name: Deploy UI
    uses: ./.github/workflows/reusable-deploy.yaml
    with:
      component: apps/ui
    secrets:
{% raw -%}
      fly-api-token: ${{ secrets.FLY_API_TOKEN }}
{% endraw %}
    needs: [ test-ui ]