openapi: "3.1.0"
info:
  version: 0.1.0
  title: {{ cookiecutter.repo_name }} API
  description: An API for getting bin collection details from Reading council
paths:
  /addresses/{postcode}:
    get:
      description: Returns list of addresses that match the given postcode
      operationId: get-addresses
      parameters:
        - name: postcode
          in: path
          description: Postcode of the addresses to retrieve
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Addresses matching postcode
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Addresses'
        default:
          description: Default error message to return to clients
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Status'
  /collection/subscribe:
    post:
      description: Subscribe to bin collection notifications
      operationId: subscribe
      requestBody:
        description: Subscription details to add for bin collection notifications
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Success'
      responses:
        '202':
          description: Subscription successfully acknowledged
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Status'
        '409':
          description: An active subscription already exists
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Status'        
        default:
          description: Default error message to return to clients
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Status'
  # TODO: This shouldn't be publicly accessible - make it obvious in API schema
  /collection/subscribe/{subscriptionId}: 
    get:
      description: Get the details of an existing subscription based on its ID
      operationId: get-subscription-details
      parameters:
        - name: subscriptionId
          in: path
          description: ID of the subscription being queried
          required: true
          schema:
            type: string
      responses:
        '202':
          description: Subscription successfully acknowledged - still pending
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Status'
        '201':
          description: Subscription successfully created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Status'        
        default:
          description: Default error message to return to clients
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Status'
        
# Using RFC3986 for external referencing of schemas: https://swagger.io/docs/specification/using-ref/
components:
  schemas:
    Success:
      type: object
    Subscription:
      type: object
      required:
        - mobileNumber
        - siteUprn
      properties:
        mobileNumber:
          type: string
          description: The mobile number in which to receive bin collection notifications
        siteUprn:
          type: string
          description: The UPRN that uniquely identifies a subscriber's bin collection schedule based on their address
    Status:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
    Address:
      type: object
      description: Bin collection point address - as referenced in https://api.reading.gov.uk/v0.json#/components/schemas/Address'
      required:
      properties:
        AccountSiteId:
          type: string
          example: '71454'
        AccountSiteUprn:
          type: string
          example: '310072455'
        SiteAddress2:
          type: string
          example: 'ST GILES CLOSE'
        SiteAddressPrefix:
          type: string
          example: 'None'
        SiteEasting:
          type: string
          example: '471811.0'
        SiteId:
          type: string
          example: '64711'
        SiteLatitude:
          type: string
          example: '51.4510090644'
        SiteLongitude:
          type: string
          example: '-0.967964890157'
        SiteNorthing:
          type: string
          example: '172954.0'
        SiteShortAddress:
          type: string
          example: 'ALDER HOUSE, FLAT 1, ST GILES CLOSE, RG1 2AR'
    Addresses:
      type: array
      description: List of addresses - as referenced in https://api.reading.gov.uk/v0.json#/components/schemas/Addresses'
      items:
        $ref: '#/components/schemas/Address'